Document: binutils
Title: Debian binutils Manual
Author: <insert document author here>
Abstract: This manual describes what binutils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/binutils/binutils.sgml.gz

Format: postscript
Files: /usr/share/doc/binutils/binutils.ps.gz

Format: text
Files: /usr/share/doc/binutils/binutils.text.gz

Format: HTML
Index: /usr/share/doc/binutils/html/index.html
Files: /usr/share/doc/binutils/html/*.html
